config/routes.rb
Rails.application.routes.draw do
  root to:redirect('/events')
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order(:date)
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :imageurl, :date, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def timeLeft(eventDate,eventTime)
		
		currentDate = Date.today
		currentTime = Time.now
		eventDateTime = eventDate + eventTime.seconds_since_midnight.seconds

		timeLeft = eventDateTime - Time.now 
		result = ""

		if timeLeft < 0
			return "EXPIRED"	
		
		else 
					
			daysLeft = (eventDate - currentDate).floor 

			if daysLeft == 1
				result += daysLeft.to_s + " Day "

			elsif daysLeft > 1
				result += daysLeft.to_s + " Days "
			end
			
			hoursLeft = (((eventDateTime - Time.now) /3600).round) - (daysLeft*24)

			if hoursLeft == 1
				result += hoursLeft.to_s + " Hour "

			elsif hoursLeft > 1
				result += hoursLeft.to_s + " Hours "
			end		
			
		end			

		result += "Left"

		return result;

	end

end

app/views/events/_form.html.erb
<div class="row newEventContainer">

  <!--side -->
  <div class="col-lg-3 col-md-0 col-sm-0 col-xs-0"></div>

  <!-- center content -->
  <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">

    <%= form_for(event) do |f| %>
        
        <% if event.errors.any? %>
        
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
              <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

    <div class="field bottomPadding5px">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "textField" %>
    </div>

    <div class="field bottomPadding5px">
      <%= f.label :description %>
      <%= f.text_area :description, :class => "textField newEventDescriptionField" %>
    </div>

    <div class="field bottomPadding5px">
      <%= f.label :"Image URL" %>
      <%= f.text_field :imageurl, :class => "textField" %></br></br>

      Please insert an image url.<br/> 
      For example, try: http://i.imgur.com/egAq1cf.jpg <br/><br/>
      The image should have a minimum width of 1280px.

    </div>

    <div class="field bottomPadding20px">
      <%= f.label :date %>
      <%= f.date_select :date %>
    </div>

    <div class="field bottomPadding20px">
      <%= f.label :"Time (24 Hours)" %>
      <%= f.time_select :time %>
    </div>

    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="actions">
          <%= f.submit :class => "redBtn btn-block" %>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
    </div>


    <% end %>


  </div>

  <!--side -->
  <div class="col-lg-3 col-md-0 col-sm-0 col-xs-0"></div>

</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

  <!-- Events Title -->
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-4 col-xs-4"><h1>Events</h1>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-8 col-xs-8 indexAddEvents"><%= link_to 'Add New Event', new_event_path, class: "redBtn" %></div>

  </div>

<!-- Events Listing -->

  <% @events.each do |event| %>

  <div class="row indexRowEvent">

    <!-- image -->
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">    
      <%= image_tag(event.imageurl, class: "img-responsive text-center") if event.imageurl.present? %><br/>
    </div>

    <!-- events description -->
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
      <div class="indexEventDate"><%= event.date.strftime("%d %b %Y %A") %> <%= event.time.strftime("%l:%M %p") %> <span class="indexEventDateHidden" id= <%= event.date%> ><%= event.date%></span> </div> 

      <div class="indexEventTimeLeft"> <%= timeLeft(event.date,event.time) %> </div> 
  
      <div class="indexEventTitle"><%= event.title %></div> 
      <div class="indexEventDescript"><%= event.description %> </div>

      <div class="indexEventLinks">     
        <%= link_to 'View', event, class:"indexEventLinksBtn" %> &nbsp;
        <%= link_to 'Edit', edit_event_path(event), class:"indexEventLinksBtn" %> &nbsp;
        <%= link_to 'Delete', event, class:"indexEventLinksBtn", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>  
    </div>

  </div> 

  <% end %>

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row newEventContainer text-center">

  <!--side -->
  <div class="col-lg-2 col-md-0 col-sm-0 col-xs-0"></div>

  <!-- center content -->
  <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 text-center">

    <p id="notice"><%= notice %></p>

    <!-- Event Title -->
    <div class="viewEventContentContainer">
      <strong>Title:</strong> <%= @event.title %>
    </div>

    <div class="viewEventContentContainer"> 
      <strong>Date:</strong> <%= @event.date.strftime("%d %b %Y %A") %> 
    </div>

    <div class="viewEventContentContainer"> 
      <strong>Time:</strong> <%= @event.time.strftime("%l:%M %p") %>
    </div>

    <!-- Event Description -->  
    <div class="viewEventContentContainer"> 
      <strong>Description:</strong>
    </div>


    <div class="viewEventContentContainer"> 
      <%= @event.description %>
    </div>

    <!-- Event Image -->
    <div class="viewEventContentContainer"> 
      <strong>Image:</strong>
    </div>

    <div class="viewEventContentContainer"> 
      <%= image_tag(@event.imageurl, class: "img-responsive text-center") if @event.imageurl.present? %>
    </div>



    <div class="viewEventButtonsContainer">   

      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 viewEventButtonHolder">
        <%= link_to 'Edit', edit_event_path(@event), class: "redBtn btn-block"  %>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 viewEventButtonHolder">
        <%= link_to 'Back', events_path, class: "whiteBtn btn-block" %>
      </div>
      
      
      

    </div>

  </div>  

  

  <!--side -->
  <div class="col-lg-2 col-md-0 col-sm-0 col-xs-0"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Events</title>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<!-- navigation bar -->
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Events App</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="/ideas">Events</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">

		<div class="row">

			<!--side -->
			<div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>

			<!-- center content -->
			<div class="col-lg-10 col-md-12 col-sm-12 col-xs-12">
				<%= yield %>
			</div>

			<!--side -->
			<div class="col-lg-1 col-md-0 col-sm-0 col-xs-0"></div>

			</div>
		<footer>
			<div class="container text-center">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					Huang Yanying 2016
				</div>
			</div>
		</footer>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>	
	</body>
	</html>